apiVersion: v1 
kind: Pod
metadata:
  name: pod-config
spec:
   containers:
   - name: nginx
     image: nginx
     envFrom:
     - configMapRef:
       name: devopswithaws
    #  env:
    #  - name: course
    #    valueFrom:
    #      configMapKeyRef:
    #        name: devopswithaws
    #        key: course
    #  - name: trainer
    #    valueFrom:
    #      configMapKeyRef:
    #        name: devopswithaws
    #        key: trainer